### ISSUE TITLE
Add documentation support

### ISSUE THREAD

**Issue by devacfr** [devacfr/reflow-maven-skin#19]
A document navigation page should facilitate the navigation through a tree of pages.

## Design
![sans titre](https://user-images.githubusercontent.com/2300004/35470873-645962ba-0351-11e8-9d96-68abd429c51b.png)

The `sidenav` is list of  chapters that possible to organize in section. Each chapter represents a file displayed in `content frame`. a `toc sidebar` is appended.

## To Do List

- [x] Bootstrap 4 support.
- [x] Add rendering type (page,doc,frame)
- [x] Rendering sub-item
- [x] Add icon on top level item only
- [x] Add `toc` attribute to menu item to disable toc sidebar ( default **true**)
- [x] Add routing by url fragment, empty route loads the default chapter (first of list).
- [x] Allow to auto collapse of toc sidebar on scrollspy with `collapsed` attribute on toc element
- [x] Activation feature by css class on body element.
- [x] Select the first sub-item on show collapse of top level item.
- [x] Include heading in url fragment http://localhost/document.html#slug-page-name.heading-id
- [x] Show collapse of sub-menu when a sub-item is selected after loaded page.
- [x] Refactor scroll to top button
- [x] Refactoring documentation
- [X] Add theme on navside element.
- [x] Add Bootstrap theme on footer element.
- [x] ToC sidebar doesn't hidden when window size < lg.
- [x] Apply offset with scrollspy on toc top and toc sidebar.
- [x] add migration doc replace #bannerRight #bannerLeft by .bannerRight .bannerLeft
- [x] Fusion Configuration and Get Started document.
- [x] Replace `<sidebar>` layout by bootstrap card.
- [x] Update javadoc.
- [x] Add doc on navside menu
- [x] Add doc on footer element
- [x] Update documentation
- [ ] ~~Add Viewport type by  css class on body element .~~

**Comment by devacfr** [comment]
## TODO after commit 6a4e1fd
- rendering sub-item
- add icon for item and sub-item
- refactoring documentation
- update documentation

**Comment by solomax** [comment]
I just have started testing (using locally built version from `develop` branch)
Features not working so far:

1. theme: https://github.com/apache/openmeetings/blob/master/src/site/site.xml#L66
2. endContent: https://github.com/apache/openmeetings/blob/master/openmeetings-server/src/site/site.xml#L138

will try to do some more testing tomorrow

**Comment by solomax** [comment]
Additionally `velocity.log` is being created in the root of the project tree

**Comment by devacfr** [comment]
@solomax 
- set `<localResources>`**true**`</localResources>`
- to use theme "cerulean" set to `bootswatch-cerulean` (see https://devacfr.github.io/reflow-maven-skin/skin/themes/bootswatch-cerulean.html). 
```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack</id>
            <phase>pre-site</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>io.github.devacfr.maven.skins</groupId>
                  <artifactId>reflow-default-webdeps</artifactId>
                  <version>${project.version}</version>
                  <type>jar</type>
                  <overWrite>false</overWrite>
                  <includes>
                    **/css/fontawesome/*, <!-- add all awesome -->
                    **/css/themes/cerulean/*.css, <!-- add specific theme -->
                    **/js/*.js,  <!-- add all javascripts -->
                    **/js/languages/*,  <!-- add all highlight languages -->
                    **/js/styles/default.min.css <!-- add 'default' highlight style -->
                  </includes>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${main.basedir}/target/site</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
**Note**: main.basedir equals to `${session.executionRootDirectory}` for relativize url (see https://devacfr.github.io/reflow-maven-skin/skin/multi-module.html )

- "site" used to customize theme (see https://devacfr.github.io/reflow-maven-skin/skin/themes/).
-  for "endcontent" maybe Oops...

**Comment by solomax** [comment]
@devacfr 
All this is actually done: 

theme and local resources:
https://github.com/apache/openmeetings/blob/new-reflow-site/src/site/site.xml#L65

resource unpacking:
https://github.com/apache/openmeetings/blob/new-reflow-site/openmeetings-server/pom.xml#L228

As far as I can see `reflow-default-webdeps` has no themes in it

**Comment by devacfr** [comment]
@solomax, in site.xml 
I think this is wrong `<theme>bootswatch-${reflow-theme}</theme>` , normally
`<theme>bootswatch-${this.reflow-theme}</theme>` see  Interpolation 
 in https://maven.apache.org/plugins/maven-site-plugin/migrate.html.
I recommend to remove minus character.

**Comment by solomax** [comment]
@devacfr this works as expected if reflow 1.4.2/1.5.0 is used
I'll try to change `reflow-theme` with `reflow.theme`, but I doubt it will help

**Comment by devacfr** [comment]
@solomax, if that's works fine ok, but not use '.'  dot character.

**Comment by solomax** [comment]
Hello @devacfr,

theme and endContent is now being loaded as expected, thanks!

Is there any way to provide top navbar css class?
I found `<toc cssClass="navbar-dark bg-primary border rounded">top</toc>` only

`velocity.log` is still being generated in project root folder, is it possible to create it in `target` folder?

It seems following XML is not being correctly processed:
```
		<section name="Community">
			<div class="bd-callout bd-callout-info">
				<h4>Who we are</h4>
				<span><a href="team.html">List of committers</a>.</span>
			</div>
			<div class="bd-callout bd-callout-info">
				<h4>Users!</h4>
				<span>We'd love to have you involved. Check out the <a href="get-involved.html">Get involved</a>.</span>
			</div>
		</section>
```
You can check the result here: https://om.alteametasoft.com:8443/next/docs/#_toc_community

**Comment by devacfr** [comment]
Hi @solomax 
- you can change the default color and style of toc using `cssClass` attribute ex: "navbar-light bg-light" or "navbar-dark bg-primary".
- I try to find how disable velocity.log output
- for error, I must fork your project to check. a html element isn't close correctly (I will verify friday).

**Comment by solomax** [comment]
Hello @devacfr,

navbar is being generated for me by this plugin
I have modified my site.xml as follows:
`<toc cssClass="navbar-dark bg-primary" type="fixed">sidebar</toc>`
with no effect :(

Specified CSS classes were NOT added to both top navbar and sidebar

**Comment by devacfr** [comment]
Hi @solomax, 
I changed attribute `type` by `position` in `<toc position="fixed|relative" >sidebar</toc>`  element.
to change css in navbar. add `<navbar cssClass="navbar-light bg-light border-bottom|bootstrap classes">` element.

For more information [migration](https://github.com/devacfr/reflow-maven-skin/blob/develop/reflow-maven-skin/src/site/markdown/migration.md)

**Comment by solomax** [comment]
It works
Thanks a lot :)

Only one minor issue remains: `html element isn't close correctly`
Let me know when it will be time to test it :)

**Comment by devacfr** [comment]
@solomax 
FYI, I replace `<topNav>` element by `filterMenu` attribute on `navbar` element.

For more information [migration](https://github.com/devacfr/reflow-maven-skin/blob/develop/reflow-maven-skin/src/site/markdown/migration.md#navbar-component)

**Comment by solomax** [comment]
Thanks @devacfr, I haven't used `topNav` :)

**Comment by devacfr** [comment]
Hi @solomax 
I generate the site with reflow and without, I have same result. I believe the error is in `maven doxia` project, but I don't where exactly. I continue to find

——————— without reflow
```xml
<div class="section">
<h2><a name="Community"></a>Community</h2>	
<div class="bd-callout bd-callout-info">
				
<div class="section">
<div class="section">
<h4><a name="Who_we_are"></a>Who we are</h4>
				<span><a href="team.html">List of committers</a>.</span>
			</div>
			
<div class="bd-callout bd-callout-info">
				</div>
<div class="section">
<h4><a name="Users.21"></a>Users!</h4>
				<span>We'd love to have you involved. Check out the <a href="get-involved.html">Get involved</a>.</span>
			</div>
		</div></div></div>
```

——————— with reflow

```xml
<div class="section">
<h2><a name="Community"></a>Community</h2>	
<div class="bd-callout bd-callout-info">
				
<div class="section">
<div class="section">
<h4><a name="Who_we_are"></a>Who we are</h4>
				<span><a href="team.html">List of committers</a>.</span>
			</div>
			
<div class="bd-callout bd-callout-info">
				</div>
<div class="section">
<h4><a name="Users.21"></a>Users!</h4>
				<span>We'd love to have you involved. Check out the <a href="get-involved.html">Get involved</a>.</span>
			</div>
		</div></div></div>
```xml

**Comment by devacfr** [comment]
Hi @solomax,
If you replace <h4> element by a stuf  like this <div class="font-weight-bold">, Its works.

**PS**: I'm on vacation for a week. I would implement the theme on footer before release a beta version.

**Comment by solomax** [comment]
it seems formatting was lost :(
Could you update your comment?

Here http://openmeetings.apache.org/ it seems to be displayed correctly ...

**Comment by devacfr** [comment]
@solomax,
I used reflow 1.4.2, 1.5.0 and 2.0.0 with on branch new-reflow-site. I'm trying without reflow skin. I used site 3.6. restore decoration xsd 1.6. I have same result. I don't undestand the reason. Now, I will try using release 4.0.6-RC1 and reflow 2.0.0

**Comment by devacfr** [comment]
Hi @solomax 

the release 4.0.6-RC1 doesn't use heading in callout...

```xml
<section name="Community">
			<div class="bs-callout bs-callout-info">
				<b>Who we are</b>
				<span><a href="team.html">List of committers</a>.</span>
			</div>
			<div class="bs-callout bs-callout-info">
				<b>Users!</b>
				<span>We'd love to have you involved. Check out the <a href="get-involved.html">Get involved</a>.</span>
			</div>
		</section>
```

**Comment by solomax** [comment]
Thanks @devacfr 
Totally forgot about this change, will change it to `b` and will play with CSS
Thanks a lot!

**Comment by devacfr** [comment]
Maxim,
No problem, its appends😀

**Comment by devacfr** [comment]
Reflow version 2.0.0-beta1 has been released.

**Comment by chabala** [comment]
Sorry to ping a closed issue, but I see mentioned here a few times that `velocity.log` was appearing in your project root. Did you discover why and how to prevent that?

**Comment by devacfr** [comment]
@chabala see commit https://github.com/devacfr/reflow-maven-skin/commit/d68df55faeec0f143e0fe58cc900d3b330ab9369. add src/main/resources/org/apache/velocity/runtime/defaults/velocity.properties file in your project or change property runtime.log = target/velocity.log
